# Generated by Django 5.0.1 on 2026-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superAdmin', '0003_deliveryagentapprovallog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home_kitchen', 'Home & Kitchen'), ('beauty_personal_care', 'Beauty & Personal Care'), ('sports_fitness', 'Sports & Fitness'), ('toys_games', 'Toys & Games'), ('automotive', 'Automotive'), ('grocery', 'Grocery'), ('books', 'Books'), ('services', 'Services'), ('other', 'Other')], max_length=50, null=True, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.AlterField(
            model_name='deliveryagentapprovallog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productapprovallog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorapprovallog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
