# Generated by Django 5.0.1 on 2026-02-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superAdmin', '0004_commissionsetting_alter_deliveryagentapprovallog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionsetting',
            name='basic_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
