# Generated by Django 6.0.1 on 2026-02-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_review_updated_at_review_reviewer_name_and_more'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vendorreview',
            name='order',
        ),
        migrations.RemoveField(
            model_name='vendorreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendorreview',
            name='vendor',
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='user.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('Product', 'user')},
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
        migrations.DeleteModel(
            name='VendorReview',
        ),
    ]
