# Generated by Django 5.0.1 on 2026-02-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_order_status_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
