# Generated by Django 5.0.1 on 2026-02-21 23:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAgent', '0004_deliveryagentprofile_last_location_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagentprofile',
            name='id_proof_file',
        ),
        migrations.RemoveField(
            model_name='deliveryagentprofile',
            name='license_file',
        ),
        migrations.RemoveField(
            model_name='deliveryagentprofile',
            name='vehicle_insurance',
        ),
        migrations.RemoveField(
            model_name='deliveryagentprofile',
            name='vehicle_registration',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='delivery_photo',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='signature_image',
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='id_proof_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='id_proof_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='id_proof_mimetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='license_file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='license_file_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='license_file_mimetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='vehicle_insurance_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='vehicle_insurance_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='vehicle_insurance_mimetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='vehicle_registration_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='vehicle_registration_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='vehicle_registration_mimetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='delivery_photo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='delivery_photo_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='delivery_photo_mimetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='signature_image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='signature_image_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='signature_image_mimetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliverycommission',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliverycommission',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
