# Generated by Django 5.0.1 on 2026-02-21 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_orderitem_commission_amount_and_more'),
        ('vendor', '0002_remove_productimage_image_productimage_image_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_type', models.CharField(choices=[('credit', 'Credit (Earnings)'), ('debit', 'Debit (Deduction/Withdrawal)')], max_length=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='vendor.vendorprofile')),
            ],
            options={
                'verbose_name_plural': 'Ledger Entries',
            },
        ),
    ]
