# Generated by Django 5.0.1 on 2026-02-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home_kitchen', 'Home & Kitchen'), ('beauty_personal_care', 'Beauty & Personal Care'), ('sports_fitness', 'Sports & Fitness'), ('toys_games', 'Toys & Games'), ('automotive', 'Automotive'), ('grocery', 'Grocery'), ('books', 'Books'), ('services', 'Services'), ('other', 'Other')], max_length=50, unique=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('basic_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
