# Generated by Django 5.0.1 on 2026-02-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_commissionsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommissionSetting',
        ),
    ]
